version: "3.9"

services:
  jenkins:
    container_name: jenkins-service
    image: jenkins/jenkins
    privileged: true
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker

